### TASK DAY 3


##### Task 1.4.1: Given a 6×6 matrix of random integers 1–100, extract all elements that are divisible by both 3 and 5.

In [4]:
import numpy as np
arr= np.random.randint(1,101,(6,6))
print("6x6 array is::")
print(arr)
res= arr[(arr%3==0) & (arr%5==0)]
print("No divisible by both 3 an 5 are")
print(res)


6x6 array is::
[[55 18 31 87 52 58]
 [17 51 79 67 67 68]
 [65 45 36 96 32  6]
 [26 82 62 10 22 88]
 [ 3 18 69 81 84 73]
 [ 6 47 99 62 36 73]]
No divisible by both 3 an 5 are
[45]


##### Task 1.4.2: Use np.where to replace all values below the mean of an array with 0 and above with 1 (binarise). 

In [6]:
arr=np.array([12,34,56,76,23,68,9,3,12,59])
means=np.mean(arr)
arr1=np.where(arr<means,0,1)
print("Resultant binray array is::")
print(arr1)

Resultant binray array is::
[0 0 1 1 0 1 0 0 0 1]


##### Task 1.4.3: Use np.ix_ to extract a 3×3 sub-matrix from rows [1,3,4] and columns [0,2,4] of a 5×5 array.

In [8]:
arr= np.random.randint(1,101,(5,5))
print("5x5 array is::")
print(arr)
rows=[1,3,4]
columns=[0,2,4]
sub=arr[np.ix_(rows,columns)]
print("sub matirx are:")
print(sub)

5x5 array is::
[[75 35 70 49 81]
 [59 46 30  8 46]
 [29 87 43 37 11]
 [24 16 94 66 65]
 [20 77 58  8 16]]
sub matirx are:
[[59 30 46]
 [24 94 65]
 [20 58 16]]


##### Task 1.4.4: Sort a 4×4 random matrix row-wise and column-wise separately (without loops).

In [12]:
arr= np.random.randint(1,101,(4,4))
print("4x4 array is::")
print(arr)
print("Row wise sorting")
print(np.sort(arr, axis=1)) 
print("Column wise sorting")
print(np.sort(arr, axis=0))  

4x4 array is::
[[36  6 17  3]
 [ 3 65 41 12]
 [52 69 80 45]
 [33 39 25 18]]
Row wise sorting
[[ 3  6 17 36]
 [ 3 12 41 65]
 [45 52 69 80]
 [18 25 33 39]]
Column wise sorting
[[ 3  6 17  3]
 [33 39 25 12]
 [36 65 41 18]
 [52 69 80 45]]


##### Task 1.4.5: Use np.select to classify 15 random scores into: 'A'(≥85), 'B'(≥70), 'C'(≥55), 'D'(≥40), 'F'(below 40). 

In [15]:
scoree=np.array([59,79,98,63,83,60,99,81,59])
scores=[scoree>= 85,scoree >= 70,scoree>=55, scoree >= 40]
label=["A","B","C","D"]
res= np.select(scores,label,default="F")
print(res)



['C' 'B' 'A' 'C' 'B' 'C' 'A' 'B' 'C']


### BROACASTING

##### Add [1,2,3,4] to every row and subtract [10,20,30,40,50] from every column.


In [16]:
import numpy as np

# Create 5x4 random matrix
matrix = np.random.randint(1, 20, (5, 4))

print("Original Matrix:")
print(matrix)

# Add to every row
row_add = np.array([1, 2, 3, 4])

# Subtract from every column
col_sub = np.array([10, 20, 30, 40, 50]).reshape(5, 1)

# Broadcasting operations
result = matrix + row_add - col_sub

print("\nResult Matrix:")
print(result)

Original Matrix:
[[ 2 11 10  6]
 [ 9  4  4 11]
 [ 5 11 12 19]
 [ 3 19 19 14]
 [12  2  4 10]]

Result Matrix:
[[ -7   3   3   0]
 [-10 -14 -13  -5]
 [-24 -17 -15  -7]
 [-36 -19 -18 -22]
 [-37 -46 -43 -36]]


#####  Normalise each column of a 6×4 random matrix to have mean=0 and std=1 using broadcasting.

In [17]:
import numpy as np

# Generate 6x4 random matrix
matrix = np.random.randint(1, 100, (6, 4))

print("Original Matrix:")
print(matrix)

# Column-wise mean and std
mean = np.mean(matrix, axis=0)
std = np.std(matrix, axis=0)

# Normalization using broadcasting
normalized = (matrix - mean) / std

print("\nNormalized Matrix:")
print(normalized)

print("\nColumn Means:")
print(np.mean(normalized, axis=0))

print("\nColumn Standard Deviations:")
print(np.std(normalized, axis=0))

Original Matrix:
[[23 17 74 26]
 [61 45 69 73]
 [62 50 27 91]
 [34 36 47 76]
 [34 29 55 13]
 [29 91 65 22]]

Normalized Matrix:
[[-1.14340016 -1.1866834   1.12907146 -0.78999427]
 [ 1.33941162  0.01429739  0.81250937  0.74640838]
 [ 1.40474877  0.22875825 -1.8466122   1.33481791]
 [-0.42469149 -0.37173215 -0.58036383  0.84447664]
 [-0.42469149 -0.67197735 -0.07386449 -1.21495671]
 [-0.75137725  1.98733726  0.55925969 -0.92075194]]

Column Means:
[0.00000000e+00 3.70074342e-17 1.85037171e-16 5.55111512e-17]

Column Standard Deviations:
[1. 1. 1. 1.]


#####   Task 2.2.3: Build a distance matrix: given 5 points on a number line, create a 5×5 matrix where entry [i,j] = |points[i] - points[j]|. Use broadcasting, no loops. 

In [18]:
import numpy as np

# Points on number line
points = np.array([2, 5, 9, 12, 20])

# Create distance matrix using broadcasting
distance_matrix = np.abs(points[:, np.newaxis] - points)

print("Points:")
print(points)

print("\nDistance Matrix:")
print(distance_matrix)

Points:
[ 2  5  9 12 20]

Distance Matrix:
[[ 0  3  7 10 18]
 [ 3  0  4  7 15]
 [ 7  4  0  3 11]
 [10  7  3  0  8]
 [18 15 11  8  0]]


In [19]:
A = np.array([[1,2],[3,4]]) 
B = np.array([[5,6],[7,8]]) 
print(A*B)
print(A@B)

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


##### Task 3.3.1: Create a random 3×3 matrix A. Verify A @ inv(A) ≈ identity using np.allclose. 

In [23]:
matrix = np.random.randint(1, 20, (3,3))
matrixI = np.linalg.inv(matrix)
print(matrix @ matrixI)

[[ 1.00000000e+00  1.40859546e-15  2.70616862e-16]
 [-8.32667268e-17  1.00000000e+00  1.38777878e-17]
 [-2.08166817e-16  2.69922973e-15  1.00000000e+00]]


##### Task 3.3.2: Solve the system: 2x+y=5, x+3y=10 using np.linalg.solve. Verify your answer. 

In [31]:
X=np.array([[2,1],[1,3]])
Y=np.array([5,10])
x = np.linalg.solve(X ,Y) 
print(x)

[1. 3.]


#####  Task 3.3.3: Generate a symmetric matrix S = A.T @ A. Compute its eigenvalues and verify they are all non-negative. 

In [33]:
A= np.random.randint(0,10,(3,3))
S = A.T @ A
eigenvalues = np.linalg.eigvals(S)

print("Matrix A:\n", A)
print("\nSymmetric Matrix S = A.T @ A:\n", S)
print("\nEigenvalues of S:\n", eigenvalues)

# Verify all eigenvalues are non-negative
print("\nAre all eigenvalues non-negative?")
print(np.all(eigenvalues >= 0))


Matrix A:
 [[7 1 8]
 [1 9 0]
 [0 0 4]]

Symmetric Matrix S = A.T @ A:
 [[50 16 56]
 [16 82  8]
 [56  8 80]]

Eigenvalues of S:
 [  6.19426483 128.58973941  77.21599576]

Are all eigenvalues non-negative?
True


##### Task 3.3.4: Compute the dot product of two random unit vectors (normalise with np.linalg.norm first). Interpret the result

In [34]:
import numpy as np

# Generate two random vectors
v1 = np.random.rand(3)
v2 = np.random.rand(3)

# Normalize them to unit vectors
u1 = v1 / np.linalg.norm(v1)
u2 = v2 / np.linalg.norm(v2)

# Compute dot product
dot_product = np.dot(u1, u2)

print("Unit Vector u1:\n", u1)
print("\nUnit Vector u2:\n", u2)
print("\nDot Product:", dot_product)

Unit Vector u1:
 [0.46258    0.86470426 0.19571992]

Unit Vector u2:
 [0.0864455  0.40763686 0.90904311]

Dot Product: 0.5703911339133292


##### Task 4.3.1: Given a 1D array of 20 random integers, find the indices of the 5 smallest and 5 largest values without fully sorting. 

In [43]:
arr= np.random.randint(1,50,20)
print(arr)
k=5
top_idx = np.argsort(arr)[-k:][::-1] 
print(arr[top_idx])
small_idx = np.argsort(arr)[:k]
print(arr[small_idx])

[29 24 10 14  9 14 40  7 17 12 19 27  2 28 36 40 24 17  3 29]
[40 40 36 29 29]
[ 2  3  7  9 10]


#####   Task 4.3.2: Sort a 5×5 matrix so each row is sorted ascending and each column is sorted ascending (hint: sort rows first, then columns).

In [44]:
import numpy as np

# Create random 5×5 matrix
A = np.random.randint(1, 50, (5, 5))

print("Original Matrix:\n", A)

# Sort each row
A = np.sort(A, axis=1)

# Sort each column
A = np.sort(A, axis=0)

print("\nMatrix after sorting rows and columns:\n", A)

Original Matrix:
 [[43 14  1 12 31]
 [48 33 32 44 33]
 [15 28 42  8  7]
 [24 31 23  4 25]
 [33 15 37  9 30]]

Matrix after sorting rows and columns:
 [[ 1  8 14 25 31]
 [ 4 12 15 28 37]
 [ 7 15 24 31 42]
 [ 9 23 30 33 43]
 [32 33 33 44 48]]


#####  Task 4.3.3: From two random integer arrays of size 15 (range 1–20), find common elements, elements only in A, and elements only in B. 

In [45]:
import numpy as np

# Create two random arrays
A = np.random.randint(1, 21, 15)
B = np.random.randint(1, 21, 15)

print("Array A:\n", A)
print("\nArray B:\n", B)

# Common elements
common = np.intersect1d(A, B)

# Elements only in A
only_A = np.setdiff1d(A, B)

# Elements only in B
only_B = np.setdiff1d(B, A)

print("\nCommon elements:", common)
print("Elements only in A:", only_A)
print("Elements only in B:", only_B)

Array A:
 [ 4  5 13 20 16 12 19 16  4  3  5  7  8 12 10]

Array B:
 [ 6 13 11 19 15 13  2  1  9  7 16  3  5 11  6]

Common elements: [ 3  5  7 13 16 19]
Elements only in A: [ 4  8 10 12 20]
Elements only in B: [ 1  2  6  9 11 15]


### FILE I/O


##### 

In [46]:
import numpy as np

# Create a 20×5 random float array
A = np.random.rand(20, 5)

# Save as .npy file
np.save("array_data.npy", A)

# Save as .csv file
np.savetxt("array_data.csv", A, delimiter=",")

# Reload both files
npy_data = np.load("array_data.npy")
csv_data = np.loadtxt("array_data.csv", delimiter=",")

# Compare arrays
print("Are original and .npy data equal?")
print(np.allclose(A, npy_data))

print("\nAre original and .csv data equal?")
print(np.allclose(A, csv_data))

Are original and .npy data equal?
True

Are original and .csv data equal?
True


#####   Task 5.3.2: Simulate a dataset of 50 students with 4 subject marks. Save to CSV. Reload and compute: class topper, subject-wise averages, and students scoring below 50 in any subject.

In [47]:
import numpy as np

# Simulate dataset: 50 students with 4 subject marks
marks = np.random.randint(35, 101, (50, 4))

# Save dataset to CSV
np.savetxt("student_marks.csv", marks, delimiter=",", fmt="%d")

# Reload dataset
data = np.loadtxt("student_marks.csv", delimiter=",")

print("Student Marks Dataset:\n")
print(data)

# Total marks of each student
total_marks = np.sum(data, axis=1)

# Class topper
topper_index = np.argmax(total_marks)

print("\nClass Topper:")
print("Student Index:", topper_index)
print("Marks:", data[topper_index])
print("Total:", total_marks[topper_index])

# Subject-wise averages
subject_avg = np.mean(data, axis=0)

print("\nSubject-wise Averages:")
print(subject_avg)

# Students scoring below 50 in any subject
below_50 = np.where(np.any(data < 50, axis=1))[0]

print("\nStudents scoring below 50 in any subject:")
print(below_50)

Student Marks Dataset:

[[ 92.  74.  93.  67.]
 [ 60.  66.  80. 100.]
 [ 47.  58.  86.  83.]
 [ 59.  53.  62.  67.]
 [ 87.  77.  99.  93.]
 [ 39.  56.  68.  59.]
 [ 56.  57.  58.  66.]
 [ 40. 100.  68.  89.]
 [ 97.  69.  37.  91.]
 [ 65.  75.  50.  78.]
 [ 74.  38.  58.  50.]
 [ 40.  85.  97.  91.]
 [ 85.  70.  92.  56.]
 [ 85.  57.  74.  55.]
 [ 99.  96.  42.  44.]
 [ 36.  47.  81.  94.]
 [ 51.  38.  71.  51.]
 [ 39.  72.  42.  41.]
 [100.  87.  74.  79.]
 [ 61.  93.  51.  58.]
 [ 70.  37.  64.  43.]
 [ 76.  71.  91.  75.]
 [ 36.  82.  51.  55.]
 [ 59.  99.  74.  36.]
 [ 47.  82.  78.  41.]
 [ 65.  94.  37.  79.]
 [ 72.  83.  66.  63.]
 [ 83.  47.  58.  90.]
 [ 64.  48.  38.  86.]
 [ 93.  78.  58.  99.]
 [ 71.  62.  40.  94.]
 [ 93.  85.  99.  85.]
 [ 36.  40.  45.  79.]
 [ 81. 100.  56.  57.]
 [ 82.  97.  84.  74.]
 [ 96.  44.  45.  74.]
 [ 79.  44.  85.  77.]
 [ 93.  91.  87.  74.]
 [ 46.  56.  46.  75.]
 [ 98.  66.  43.  66.]
 [ 61.  76.  86.  46.]
 [ 96.  73.  52.  58.]
 [ 74.  68

### Performance & Vectorisation

#####   Task 6.3.1: Rewrite the following loop using vectorisation: result = []; for i in range(len(x)): result.append(x[i]**2 + 2*x[i] + 1). Benchmark both. 

In [48]:
import numpy as np
import time

# Create random array
x = np.random.rand(1000000)

# Using loop
start = time.time()

result_loop = []
for i in range(len(x)):
    result_loop.append(x[i]**2 + 2*x[i] + 1)

end = time.time()
loop_time = end - start

# Using vectorisation
start = time.time()

result_vector = x**2 + 2*x + 1

end = time.time()
vector_time = end - start

print("Loop Time:", loop_time)
print("Vectorised Time:", vector_time)

# Verify both results are same
print("\nResults equal?")
print(np.allclose(result_loop, result_vector))

Loop Time: 1.2044050693511963
Vectorised Time: 0.013555049896240234

Results equal?
True


##### Task 6.3.2: Use np.einsum to compute the outer product of two vectors and verify it matches np.outer. 

In [ ]:

# Create vectors
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Outer product using einsum
outer_einsum = np.einsum('i,j->ij', a, b)

# Outer product using np.outer
outer_np = np.outer(a, b)

print("Outer Product using einsum:\n", outer_einsum)

print("\nOuter Product using np.outer:\n", outer_np)

# Verify equality
print("\nAre both equal?")
print(np.array_equal(outer_einsum, outer_np))

#####   Task 6.3.3: Generate a float32 and float64 array of 1M elements. Compare memory usage and computation speed for squaring each.

In [49]:
import numpy as np
import time

# Create arrays
arr32 = np.random.rand(1000000).astype(np.float32)
arr64 = np.random.rand(1000000).astype(np.float64)

# Memory usage
print("float32 Memory:", arr32.nbytes / (1024**2), "MB")
print("float64 Memory:", arr64.nbytes / (1024**2), "MB")

# Benchmark float32
start = time.time()
sq32 = arr32 ** 2
end = time.time()

time32 = end - start

# Benchmark float64
start = time.time()
sq64 = arr64 ** 2
end = time.time()

time64 = end - start

print("\nfloat32 Squaring Time:", time32)
print("float64 Squaring Time:", time64)

float32 Memory: 3.814697265625 MB
float64 Memory: 7.62939453125 MB

float32 Squaring Time: 0.002999544143676758
float64 Squaring Time: 0.0029993057250976562
